language: python
env:
  - TOXENV=py38
python:
  - '3.8'
install:
  - pip install -r requirements.txt
script:
  - coverage run -m unittest discover
after_success:
  - coveralls
branches:
  only:
    - dev
    - master